#!/usr/bin/env python3
"""Generate map/boroughs.js — the simplified NYC borough vector basemap.

Fetches public NYC borough boundaries, simplifies them, and writes them as a JS
file (so the map loads them over file:// without fetch/CORS). This is a vector
basemap, so the maps render an outline with NO external tile dependency.

Run once (or when you want to refresh the geometry):
    pip install shapely
    python3 build_boroughs.py

Requires internet for the one-time source fetch. boroughs.js is committed, so
you normally don't need to re-run this.
"""
import json, urllib.request
from pathlib import Path
from shapely.geometry import shape, mapping, MultiPolygon
from shapely.ops import transform

SRC = ("https://raw.githubusercontent.com/codeforgermany/click_that_hood/"
       "main/public/data/new-york-city-boroughs.geojson")
OUT = Path(__file__).resolve().parent / "map" / "boroughs.js"
TOL = 0.0007        # simplify tolerance (~70m)
MIN_AREA = 0.00012  # drop polygon specks (tiny islands)

def main():
    with urllib.request.urlopen(SRC, timeout=30) as r:
        src = json.load(r)
    feats = []
    for f in src["features"]:
        g = shape(f["geometry"]).simplify(TOL, preserve_topology=True)
        if g.geom_type == "MultiPolygon":
            polys = [p for p in g.geoms if p.area >= MIN_AREA] or list(g.geoms)
            g = MultiPolygon(polys)
        g = transform(lambda *a: [round(c, 4) for c in a], g)
        feats.append({"type": "Feature",
                      "properties": {"name": f["properties"]["name"]},
                      "geometry": mapping(g)})
    fc = {"type": "FeatureCollection", "features": feats}
    js = ("// NYC borough outlines (simplified from NYC open data via click_that_hood).\n"
          "// AUTO-GENERATED by build_boroughs.py — vector basemap for the maps.\n"
          "const NYC_BOROUGHS = " + json.dumps(fc, separators=(",", ":")) + ";\n")
    OUT.write_text(js)
    print(f"Wrote {OUT} ({round(len(js)/1024)} KB, {len(feats)} boroughs).")

if __name__ == "__main__":
    main()
