#!/usr/bin/env python3
"""Generate map/places.js from the frontmatter of every place in places/.

Scans places/*.md, pulls the scalar frontmatter fields, and writes any entry
that has numeric lat/lng into map/places.js as `const PLACES = [...]`.

Loaded via a <script> tag (not fetch), so map.html works by double-click
(file://) as well as on GitHub Pages. Re-run after adding or moving a place:

    python3 build_map.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PLACES_DIR = ROOT / "places"
OUT = ROOT / "map" / "places.js"

# scalar fields we care about for the map
FIELDS = ["name", "type", "category", "neighborhood", "borough",
          "lat", "lng", "cost", "age_range", "indoor", "parking"]


def strip_comment(val: str) -> str:
    """Drop a trailing ' # ...' inline comment, then surrounding quotes/space."""
    val = re.sub(r"\s+#.*$", "", val).strip()
    if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
        val = val[1:-1]
    return val


def parse_frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end]
    data = {}
    for line in block.splitlines():
        if not line or line[0] in " \t#":  # skip blanks, indented, comments
            continue
        m = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if not m:
            continue
        key, raw = m.group(1), strip_comment(m.group(2))
        if key in FIELDS and raw != "":
            data[key] = raw
    return data


def main():
    places = []
    for md in sorted(PLACES_DIR.glob("*.md")):
        if md.name == "_template.md" or md.name.startswith("neighborhood-"):
            continue
        fm = parse_frontmatter(md.read_text())
        try:
            lat = float(fm["lat"])
            lng = float(fm["lng"])
        except (KeyError, ValueError):
            continue  # no usable coordinates → not mappable
        places.append({
            "name": fm.get("name", md.stem),
            "category": fm.get("category", "other"),
            "neighborhood": fm.get("neighborhood", ""),
            "borough": fm.get("borough", ""),
            "cost": fm.get("cost", ""),
            "age_range": fm.get("age_range", ""),
            "indoor": fm.get("indoor", ""),
            "parking": fm.get("parking", ""),
            "lat": lat,
            "lng": lng,
            "url": f"../places/{md.name}",
        })

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(places, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// AUTO-GENERATED by build_map.py — do not edit by hand.\n"
        f"// {len(places)} mappable places.\n"
        f"const PLACES = {payload};\n"
    )
    print(f"Wrote {OUT.relative_to(ROOT)} with {len(places)} places.")


if __name__ == "__main__":
    main()
